/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf 
Author: shinnymodels (https://sketchfab.com/shinnymodels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/barbie-the-movie-barbie-box-bec035eb61b04f4ab32c4e4d0760cc49
Title: Barbie The Movie [Barbie Box]
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.barbiebox_box_0.geometry} material={materials.material} position={[0, 103.323, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[80.696, 95.745, 100.2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
